config/routes.rb
Rails.application.routes.draw do
  root 'app#index'

  post "create", to: "app#create"
  get 'create', to: 'app#red'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html       
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/employee.rb
class Employee < ApplicationRecord
    has_many :links
    validates :fname, presence: true, length:{minimum:3}
    validates :lname, presence: true, length:{minimum:3}
end

app/models/link.rb
class Link < ApplicationRecord
    belongs_to :employee
end

app/controllers/app_controller.rb
class AppController < ApplicationController
  def index
    @employee = Employee.new
    employees = Employee.where("level < 3")
    @free = []
    if !employees.empty?
      employees.each do|e| 
        if e.links.length < 3
          @free.push(["#{e.fname} #{e.lname}", e.id])
        end
      end
    end
  end

  def create
    refererId = params[:employ][:reference]
    referer = nil
    employee = nil

    fname = params[:employ][:fname].strip.capitalize
    lname = params[:employ][:lname].strip.capitalize
    email = params[:employ][:email].strip.capitalize

    if refererId
      referer = Employee.find(refererId)
      employee = Employee.new(fname: fname, lname: lname, email: email, level: referer.level+1)
      employee.save
      referer.links.build(reference: employee.id).save
      flash[:notice] = "Registration Successful"
      redirect_to root_path
    else
      if !Employee.select('id').where("level == 0").empty?
        @employ = Employee.new(fname: fname, lname: lname, email: email, level: 0)
        employees = Employee.where("level < 3")
        @free = []
        if !employees.empty?
          employees.each do|e| 
            if e.links.length < 3
              @free.push(["#{e.fname} #{e.lname}", e.id])
            end
          end
        end
        flash.now[:error] = "The system can no longer accept any more registration as the third generation is filled"
        render 'index'
      else
        employee = Employee.new(fname: fname, lname: lname, email: email, level: 0)
        employee.save
        flash[:notice] = "Registration Successful"
        redirect_to root_path
      end
    end
  end
  def red
    redirect_to root_path
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/helpers/app_helper.rb
module AppHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/app/index.html.erb
<div id="notes">
  <h1 style="text-align: center;">Skyware Pre-interview Test</h1>
  <h3 style="border-bottom: 1px solid black;">Note</h3>
    <ol>
        <li>This is based on the pre interview test specification</li>
        <li>The informations collected are basic and are just for test purpose</li>
        <li>The system is design to accomodate members up to the third generation only</li>
        <li>Modifications can be made to accept more generations if need be</li>
        <li>This app was developed using the rails framework</li>
    </ol>
</div>
<div id="form-container">
    <h1 style="text-align:center">New Member</h1>
    <% if flash[:notice] %>
      <p id="notice" class="notice">Registration Successful</p>
    <% end %>
    <% if flash[:error] %>
      <p id="notice" class="error"><%= flash[:error] %></p>
    <% end %>
    <%= form_for :employ, method: :post, url: create_path do |f| %>
      <%= f.label :fname, "First Name" %><br>
      <%= f.text_field :fname, placeholder: "First Name", required: true,  autofocus: true %><br>
      <%= f.label :lname, "Surname" %><br>
      <%= f.text_field :lname, placeholder: "Surname", required: true %><br>
      <%= f.label :email, "Email" %><br>
      <%= f.email_field :email, placeholder: "Enter Email", required: true %><br>
      <% if !@free.empty? %>
        <%= f.label :refer, "Referer" %><br>
        <%= f.select :reference, @free, class: "select" %>
      <% end %>
      <%= f.submit "Submit" %>
    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Skyware Test</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>